In [1]:
print("Hello World")

Hello World


In [3]:
x = 3+4
print(x)

7


In [8]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
import numpy as np
print(np.__version__)

1.18.1


In [11]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
boolArr = np.full((3, 3), True, dtype=bool)
boolArr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [21]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [22]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [35]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [42]:
arr = np.arange(10)
out = np.reshape(arr, (2, -1))
out

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [43]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [44]:
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [47]:
a = np.array([1,2,3])
b = np.r_[np.repeat(a, 3), np.tile(a, 3)]
b

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [49]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = list(set(a).intersection(b))
c

[2, 4]

In [53]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)


array([1, 2, 3, 4])

In [54]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)


(array([1, 3, 5, 7]),)

In [56]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a >= 5) & (a <= 10))
a[index]


array([ 6,  9, 10])

In [58]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

In [62]:
arr = np.arange(9).reshape(3,3)
arr
arr[:, [1,0,2]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [67]:
arr = np.arange(9).reshape(3,3)
arr[[0, 1]] = arr[[1, 0]]
arr

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [69]:
arr = np.arange(9).reshape(3,3)
arr[::-1]


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [70]:
arr = np.arange(9).reshape(3,3)
arr[:, ::-1]


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [73]:
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[8.67702824 6.66558244 5.2503861 ]
 [8.92039218 5.93143714 5.39719005]
 [7.09977704 7.93964332 8.35410261]
 [7.4345802  7.86018798 6.3563915 ]
 [8.18801521 7.33650634 7.35115433]]


In [74]:
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
rand_arr[:4]

array([[0.806, 0.343, 0.517],
       [0.946, 0.224, 0.674],
       [0.199, 0.208, 0.087],
       [0.583, 0.436, 0.324]])

In [79]:
a = np.arange(15)
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [90]:
import sys

np.set_printoptions(threshold=6)
a = np.arange(15)

np.set_printoptions(threshold=sys.maxsize)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [91]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [93]:
 print("I read the first 25 exersises")

I read the first 25 exersises
